import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f7f8fa",
    overflow: "hidden",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
    gap: 16,
  },
  contentWeb: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
  },
  title: {
    fontSize: 28,
    color: "#111827",
    fontFamily: "SpaceGrotesk_700Bold",
    letterSpacing: -0.2,
  },
  subtitle: {
    color: "#6b7280",
    fontSize: 14,
    marginTop: 4,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  card: {
    alignSelf: "stretch",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    padding: 24,
    gap: 10,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  label: {
    color: "#111827",
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 14,
  },
  caption: {
    color: "#6b7280",
    fontSize: 12,
    fontFamily: "SpaceGrotesk_400Regular",
    maxWidth: "100%",
    flexShrink: 1,
    minWidth: 0,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#111827",
    backgroundColor: "#ffffff",
    fontSize: 14,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  inputError: {
    borderColor: "#ef4444",
  },
  errorText: {
    color: "#ef4444",
    fontSize: 12,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  row: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  tokenInput: {
    flex: 1,
  },
  toggle: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
  },
  toggleText: {
    color: "#6b7280",
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 12,
  },
  actionRow: {
    flexDirection: "column",
    gap: 12,
    marginTop: 6,
  },
  button: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButton: {
    backgroundColor: "#2563eb",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  secondaryButton: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  secondaryButtonText: {
    color: "#6b7280",
    fontFamily: "SpaceGrotesk_500Medium",
  },
  buttonText: {
    color: "#ffffff",
    fontFamily: "SpaceGrotesk_500Medium",
  },
  statusStack: {
    alignSelf: "stretch",
    gap: 8,
    overflow: "hidden",
  },
  statusCard: {
    alignSelf: "stretch",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 6,
    overflow: "hidden",
  },
  previousCard: {
    opacity: 0.6,
    backgroundColor: "#ffffff",
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusTitle: {
    fontSize: 13,
    color: "#6b7280",
    fontFamily: "SpaceGrotesk_500Medium",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
    minWidth: 0,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusValue: {
    fontSize: 13,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  statusDetailText: {
    maxWidth: "100%",
    flexShrink: 1,
    minWidth: 0,
  },
  previousStateValue: {
    color: "#6b7280",
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 13,
  },
  errorCard: {
    alignSelf: "stretch",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fef2f2",
    padding: 12,
    gap: 4,
    overflow: "hidden",
  },
  errorCardCompact: {
    minHeight: 92,
  },
  errorTitle: {
    color: "#b91c1c",
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 13,
  },
  errorBody: {
    color: "#7f1d1d",
    fontSize: 12,
    lineHeight: 16,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
    fontFamily: "SpaceGrotesk_400Regular",
  },
  pairingCard: {
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fdba74",
    backgroundColor: "#fff7ed",
    padding: 8,
    gap: 4,
  },
  pairingTitle: {
    color: "#9a3412",
    fontFamily: "SpaceGrotesk_700Bold",
  },
  pairingBody: {
    color: "#7c2d12",
    fontSize: 11,
    lineHeight: 15,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
    fontFamily: "SpaceGrotesk_400Regular",
  },
  reconnectButton: {
    alignSelf: "flex-start",
    borderRadius: 10,
    backgroundColor: "#ea580c",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  reconnectButtonText: {
    color: "#ffffff",
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 12,
  },
  errorSlot: {
    alignSelf: "stretch",
    minHeight: 92,
    overflow: "hidden",
  },
  advancedSection: {
    alignItems: "center",
    gap: 10,
  },
  advancedLink: {
    color: "#2563eb",
    fontSize: 14,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  footerCard: {
    alignSelf: "stretch",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    padding: 12,
    gap: 6,
  },
});
